---
title: "Presentation Ninja"
subtitle: "&#x2694;&#xFE0F; xaringan +<br/>&#x1F60E; xaringanthemer"  
author: 
  - "Yihui Xie"
  - "Garrick Aden-Buie"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(xaringanthemer)
```


```{r xaringan-themer, include=FALSE, warning=FALSE}
style_solarized_light(text_color = "#657b83")
```

background-image: url(https://i.insider.com/5c17d38801c0ea08470c8fb2?width=700&format=jpeg&auto=webp)

# Group member

### Yiwen Jiang (yjia0021) 
### Yuheng Cui (ycui0008)

.footnote[
Image source: Insider https://i.insider.com/5c17d38801c0ea08470c8fb2?width=700&format=jpeg&auto=webp
]

---

# Topic

### How does relative humidity in Melbourne change throughout the day and year? When is it most uncomfortable to walk around the city?



---


